version: '3'

services:
    mongo:
        image: mongo
        container_name: mongodatastore
        tty: true
        volumes:
            - ./data/db:/data/db
        ports:
            - '27017:27017'
        networks:
            - local

    mongoclient:
        image: mongoclient/mongoclient
        container_name: mongoclient
        environment:
            - STARTUP_DELAY=10
        volumes:
            - ./data/mongoclient:/data/db
        ports:
            - '3005:3000'
        depends_on:
            - mongo
        networks:
            - local

networks:
    local:
        driver: bridge
