# Environment configuration
env_default: &env_default
    working_directory: ~/desc
    docker:
        - image: circleci/node:lts

version: 2
jobs:
    build:
        <<: *env_default
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-
            - run:
                  name: Install dependencies
                  command: yarn install
            - save_cache:
                  key: v1-dependencies-{{ checksum "package.json" }}
                  paths:
                      - 'node_modules'
            - run:
                  name: Run API unit tests
                  command: yarn test:api:unit
            - run:
                  name: Run APP unit tests
                  command: yarn test:app:all
    deploy:
        <<: *env_default
        steps:
            - checkout
            - run:
                  name: Deploy Heroku (desc-api)
                  command: |
                      git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_API_NAME.git master
            - run:
                  name: Deploy Heroku (desc-app)
                  command: |
                      git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
workflows:
    version: 2
    build-deploy:
        jobs:
            - build
                  filters:
                      branches:
                          only:
                              - master
                              - develop
            - deploy
                  requires:
                      - build
                  filters:
                      branches:
                          only: master
