name: Client Unit Tests

on:
    push:
        branches:
            - main
        paths:
            - 'packages/app/**'

    pull_request:
        branches:
            - main
            - 'feature/**'
        paths:
            - 'packages/app/**'

jobs:
    runner-job:
        name: unit tests
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install node
              uses: actions/setup-node@v1
              with:
                  node-version: '14'

            - name: Install dependencies
              run: npm install

            - name: Lint code
              run: npm run lint:app

            - name: Run unit tests
              run: npm run test:app:all
